title: Attogram Blog
author: Attogram Project
email: your-email@example.com
description: ""
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: jekyll-theme-slate

collections:
  entries:
    output: true
    permalink: /:name.html
feed:
  collections:
    entries:
      content: true

plugins:
  - jekyll-feed
